### ISSUE TITLE
My attempts to transmit images camera surveillance at internet availables

### ISSUE THREAD

**Issue by henriquem** [sarxos/webcam-capture#320]
Hello Everybody!

SomeOne have more experience than me for solved my problem ? 

I dont have idea about it, if you have some experience for clarify ! is welcome...

this camera is Tec Voice model: td2316s 

works fine in IE
http://177.103.161.26:8081  [ will ask for install webclient for run in web ]
user: admin
pass: 1
The format is h.264.

The problem is, How I could wrote in Java for transmit those images.

I copied the code bellow, but the line not response in methods s_in.read():   
    while((bytesRead = s_in.read()) > 0)

When press F12 from IE not show me in Tab Network, as Sarxos recommends in another issues when IP CAMERA is Mjpeg format.

Any Suggestions will be welcome.. 
I dont understand how the applications Mobile ( Android ) can works well done!

Or if I replace the line:
     s_in = new BufferedReader(new InputStreamReader(s.getInputStream()));
for: 

    InputStream in = new ByteArrayInputStream(toByteArray(s.getInputStream()));
    bufImage = ImageIO.read(in);

My Source Code Full
    class DVR {
    	
	          Socket s = new Socket();
    
	          public  void connect() throws Exception 
    	      {
  	      final int timeout = 10000;
    	  Authenticator.setDefault(new Authenticator()
	      {
	        protected  PasswordAuthentication  getPasswordAuthentication()
    	    {
	            System.out.println("Authenticatting...");
    	        PasswordAuthentication p=new PasswordAuthentication("admin", "1".toCharArray());
	        return p;       
    	    }
	    });
    
	    String host = "177.103.161.26";
    	PrintWriter s_out = null;
	    BufferedReader s_in = null;
    
	    try
    	{
		    s.connect(new InetSocketAddress(host, 8081),timeout); //port 8081
    	    System.out.println("Conectou? : " + s.isConnected());
	        s_out = new PrintWriter(s.getOutputStream(), true);
    	    s_in = new BufferedReader(new InputStreamReader(s.getInputStream()));
	    }
    	catch(UnknownHostException e)
	    {
	        e.printStackTrace();
    	    System.exit(1);
	    }
    	catch(Exception e)
	    {
	        e.printStackTrace();
    	    System.exit(1);
	    }
    
    
	    //bufferedInputStream.read(b);
    
	    int bytesRead = 0;
    	System.out.println("Reading... \n");
    	while((bytesRead = s_in.read()) > 0) // STOP HERE!!!!!
	    {
	        System.out.println(s_in.readLine());
	    }
      }
	private byte[] toByteArray(InputStream is) {
		try{ 
		ByteArrayOutputStream os = new ByteArrayOutputStream();
			byte[] buffer = new byte[0xFFFF];
			for (int len; (len = is.read(buffer)) != -1;)
				os.write(buffer, 0, len);
			os.flush();
			return os.toByteArray();
		} catch (IOException e) {
			return null;
		}
	}
    }

**Comment by sarxos** [comment]
Hi @henriquem,

The problem with h.264 is that there is really very few ready to use production code written in Java that is able to decode this format. Every one I take a look into has some limitations you would have to w/a when you decide to use it.

The Webcam Capture API does not (currently) support reading h.264. If you want to use it you need to configure your camera to serve MJPEG instead of h.264.

In regards to:

> When press F12 from IE not show me in Tab Network, as Sarxos recommends in another issues when IP CAMERA is Mjpeg format.

I'm not using Internet Explorer (because it sucks) and I would be completely astonished if they have such useful feature implemented. For the development I strongly suggest using [Firefox](https://www.mozilla.org/) with [Firebug plugin](https://addons.mozilla.org/en/firefox/addon/firebug/) or [Chrome](https://www.google.com/chrome/browser/desktop/), but please note that the last one has problems with rendering MJPEG, so I would stick to the Firefox.

> I dont understand how the applications Mobile ( Android ) can works well done!

Android [has](http://developer.android.com/guide/appendix/media-formats.html) its own codecs to read h.264 frames. These codecs are not available in standard Java distribution. This is the "magic" behind it working on Android and not in regular Java application.
