### ISSUE TITLE
getWebcamByName problem.

### ISSUE THREAD

**Issue by Bazmundi** [sarxos/webcam-capture#383]
I have imported 0.3.11 library into Processing and entered the following code.
```
import com.github.sarxos.webcam.Webcam;
import java.util.List;

void setup(){
  
   // I list all the cams to check the camera is seen and it is
    for (Webcam webcam : Webcam.getWebcams()) { println(webcam.getName()); }
 
   // I try the camera name I know and love but it is not found
    Webcam webcam = Webcam.getWebcamByName("MHS-FS2");
    if (webcam != null) {
      System.out.println("Webcam: " + webcam.getName());
    } else {
      System.out.println("No webcam detected");
    }
    
    // I still see the camera
    List<Webcam> cams = Webcam.getWebcams();
    System.out.println(cams.get(1).getName());
    
  // I get the code to build the string and voila!  I need to know where the camera is in the list
    webcam = Webcam.getWebcamByName(cams.get(1).getName());
    if (webcam != null) {
      System.out.println("Webcam: " + webcam.getName());
    } else {
      System.out.println("No webcam detected");
    }
    
  noLoop();
}

void draw() {
}
```

The loop through cams returns my camera in the list.  

However, the call getWebcamByName("MHS-FS2") fails with a null.  

Lifting the element (1) from the list of cams returns the "MHS-FS2 1".  

So the code concatenates the list position of the camera to the camera name which is not intuitive .  The result is a tuple and likely akin to a dictionary or map where I expect to either to recover either the key or the val etc.   

Is this something your code does or is it the OS?

If I attach multiple cameras, in different orders, I might expect that they appear in different positions in the list each time (dependant on how they are handled by OS of course).  Makes it hard to know in the code ahead of time.

I do have two bloggies so I will be curious how I will need to juggle between the two (in that case I would still have to associate a list index with one or the other bloggie ... tricky, something for me to fiddle with).

Otherwise, workable.

**Comment by sarxos** [comment]
Hi @Bazmundi,

On the OS level, every webcam is internally recognized via ID (1, 2, 3, etc). This is a number that is given by OS and it's used to address specific webcam. The webcam name is something additional, that Webcam Capture API extracts additionally so users sees the webcams by the "name + ID" instead of just "ID" (usability feature to have "Microsoft Webcam 1" instead of just "1"). 

You can find out what are the cameras names by doing:

```java
for (Webcam w : Webcam.getWebcams()) {
  System.out.println(w.getName());
}
```

The above is the "real" name that should be used to find specific webcam via the call to ```getWebcamByName(...)```.

You may ask why we cannot return single instance when calling this method? This is because you may have many webcams of the same model connected to the USB hub.

**Comment by Bazmundi** [comment]
Yep.  Gotcha.  I do note that I did get stung, having downgraded from Windoze 7 to Windoze 10, as my cameras are listed in reverse order between the two versions of the OS.  The real quirk being that the Processing Video library returns entirely a different name for the camera as it appears to print a name for each resolution of the camera and no index.  No matter, I am using your library and thankfully yours actually works ;) 

Well done!

**Comment by sarxos** [comment]
The Processing is printing supported formats together with camera names. I didn't want to do that because not all capturing frameworks that can be used under the hood of Webcam Capture API support getting info on supported formats. E.g. [OpenIMAJ](http://www.openimaj.org/) does not have it and I'm pretty almost sure that [OpenCV](http://opencv.org/) does not support it as well. The other ones like [GStreamer](http://gstreamer.freedesktop.org/), [JMF](http://www.oracle.com/technetwork/java/javase/download-142937.html), etc. has pretty nice API for this, but I wanted to keep Webcam Capture API to be common in regards to framework is being used.

Just FYI, I'm closing this ticket. If you have any further comments in regards to this issue, please do not hesitate to drop them here.
