### ISSUE TITLE
This sucks

### ISSUE THREAD

**Issue by NickNevius** [sarxos/webcam-capture#443]
Don't even try to use this shit,

**Comment by sarxos** [comment]
Hi @NickNevius,

Thank you for your opinion. 

This project has been built by community - by people like you and me, who spent their precious time to implement "this shit" for free and for everyone to use.

It's sad there are people who writes hateful comments instead of providing more details about the problem or trying to fix it by themselves :(

**Comment by hepin1989** [comment]
@NickNevius Yes,If you faced some problem ,write it down,or provide a producer ,then people could help and improve it,that will make this shit more shiny and finally become a golden shit.
