### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by alexsrs** [sarxos/webcam-capture#451]
I'm having trouble using your library in my project . I could do it compile but to run
it runs more could not put the picture in my registration scene.
My code is here https://github.com/alexsrs/rfid-eventos/

I need help, can you help me ?

**Comment by sarxos** [comment]
Hi @alexsrs, 

I'm not very familiar with JavaFX and really do not understand what is happening there :( The FXML examples for Webcam Capture has been provided by community, I'm not their author.

What I would suggest you is to embed ```WebcamPanel``` in ```SwingNode``` and use it instead of putting ```BufferedImage``` into ```ObjectProperty``` of ```ImageView``` as you did.

Moreover, what you are doing (buffered image rendering on view) is pretty badly done in JavaFX (or I'm simply too dumb to fix this example and write it properly) and cause huge GC overhead. This is another reason why I would strongly suggest to use  ```WebcamPanel``` wrapped in ```SwingNode``` instead of rendering on ```ImageView```.

http://docs.oracle.com/javafx/8/embed_swing/jfxpub-embed_swing.htm
