### ISSUE TITLE
Live Streaming Slow when compared to actual IP Camera streaming

### ISSUE THREAD

**Issue by suryarao7984** [sarxos/webcam-capture#529]
Hello, this webcam-capture project was awesome, now i want to work attendance tracking proejct with u r API using IP Camera ,so will u given any suggestions in this project.

**Comment by sarxos** [comment]
Slow streaming probably depends on the streaming format you are using. E.g. most IP cameras uses h.264 for streaming which is damn fast, however decoding h.264 in Java is pretty hard and using hardware acceleration for decoding (which is available) is impossible because you would have to write JNI for this. The IP Camera driver uses MJPEG which is slow when you compare it to h.264.
