### ISSUE TITLE
Audio capture

### ISSUE THREAD

**Issue by smilanko** [sarxos/webcam-capture#567]
While I have read several posts asking how to capture audio, and seen some examples, none use the webcam-capture library. Reading some more pointed me to a few posts stating that this library will only capture video, and not audio. As those posts date back to 2014/2015, I'd like to ask if this is still the case? If not, is there a good example of how it can be fused with the current library?

**Comment by sarxos** [comment]
Yes. Webcam Capture API library supports only image. If you would like to capture audio then you do not need any 3rd party libraries because audio capture functionality is available within Java runtime itself.

https://docs.oracle.com/javase/tutorial/sound/capturing.html

For example where Webcam Capture is fused with audio please check this live streaming example prepared by Ryan Cheu:

https://github.com/ryancheu/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-live-streaming

Take care!
