### ISSUE TITLE
should be "minSize > curSize".

### ISSUE THREAD

**Issue by kbaik** [sarxos/webcam-capture#626]
https://github.com/sarxos/webcam-capture/blob/7e82df6ba87cdff3edfc4c8318ac0f0769db4a4a/webcam-capture/src/main/java/com/github/sarxos/webcam/ds/buildin/WebcamDefaultDevice.java#L247

**Comment by sarxos** [comment]
Hi @kbaik,

Indeed, I think it should be `minSize > curSize` instead of `minSize < curSize`.

This is because:
 
* minSize = the minimal size we require to store image (required size)
* curSize = how much buffer size remaining we have (available size)

And available size should always be greater than or equal to required size and error should be throwsn otherwise. Thus `minSize > curSize`.

Can you send pull request with a fix?

**Comment by sarxos** [comment]
Fixed by @yuripourre in #631.
