### ISSUE TITLE
How can I capture and save a video (image+audio) from webcam?

### ISSUE THREAD

**Issue by jwertherf** [sarxos/webcam-capture#736]
I have seen some codes about video capture using this API (Webcam Capture), but only restricted for video images capture, i.e., video without audio (e.g. the Encoder.java sample file in this repository). I am starting a project that require this feature (capture video image and sound). Can anyone help me in show me how can I capture video and audio from the webcam at the same time and write to the same file (mp4, ts, etc.)?

**Comment by alexmao86** [comment]
this lib is used to grab Java bufferred image from vedio source.rather than vedio encoder/decoder发自我的华为手机-------- 原始邮件 --------主题：[sarxos/webcam-capture] How can I capture and save a video (image+audio) from webcam? (#736)发件人：JOÃO WERTHER 收件人：sarxos/webcam-capture 抄送：Subscribed I have seen some codes about video capture using this API (Webcam Capture), but only restricted for video images capture, i.e., video without audio (e.g. the Encoder.java sample file in this repository). I am starting a project that require this feature (capture video image and sound). Can anyone help me in show me how can I capture video and audio from the webcam at the same time and write to the same file (mp4, ts, etc.)?
