### ISSUE TITLE
which driver UVC camera  can use   MJPG 

### ISSUE THREAD

**Issue by zy5651768** [sarxos/webcam-capture#807]
I use default driver ,fps is low on ubuntu (  3-5 fps ) ,maybe change driver will good?

**Comment by alexmao86** [comment]
Hi,
Because pure Java preview panel and decoding is not high performance as native c, if your camera is 1080p, base one your PC performance, 3-5 fps make sense. 

Regarding other driver, maybe you can try JNI based driver like opencv or vlcj which are litter faster but not significant. and also you can set System properties in your launch arguments:

OpenGL or XRender is enabled to get low latency, something like
export _JAVA_OPTIONS=-Dsun.java2d.opengl=True
export _JAVA_OPTIONS=-Dsun.java2d.xrender=True

base on your hardware, maybe higher fps can be there.
Alex
